version: 2

monorepo:
  tag_prefix: go/akb/

builds:
  - id: akb
    main: ./cmd/akb/
    dir: go/akb
    binary: akb
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: akb
    ids: [akb]
    name_template: "akb_{{.Version}}_{{.Os}}_{{.Arch}}"
    files:
      - README.md
      - LICENSE

changelog:
  use: github
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug Fixes
      regexp: "^fix"
      order: 1
    - title: Other
      order: 999
